--- 
apiVersion: v1
data: 
  mapRoles: |
      - groups:
        - system:bootstrappers
        - system:nodes
        rolearn: arn:aws:iam::862515358662:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-17S84BY74COF3
        username: system:node:{{EC2PrivateDNSName}}
      - groups:
        - system:masters
        rolearn: arn:aws:iam::862515358662:role/UdacityFlaskDeployCBKubectlRole
        username: build
  mapUsers: "[]\n"
kind: ConfigMap
metadata: 
  creationTimestamp: "2020-12-14T09:09:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1626"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c93b68aa-d760-4068-aac2-11257c86ed3a
